version: '3'
services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: golfclub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "0.0.0.0:3306:3306"  # Make MySQL accessible from outside
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - golfclub-network

  golfclub-management:
    build:
      context: ../golfclub-management
    container_name: springboot
    volumes:
      - ../golfclub-management:/workspace
    ports:
      - "0.0.0.0:8080:8080"  # Expose Spring Boot backend publicly
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/golfclub
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JAVA_HOME: /docker-java-home
      SPRING_PROFILES_ACTIVE: dev
    links:
      - mysql-db:mysql-db
    depends_on:
      - mysql-db
    networks:
      - golfclub-network

  vue-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: vue-frontend
    volumes:
      - ../frontend:/workspace
    ports:
      - "0.0.0.0:8081:8081"  # Expose Vue.js frontend publicly
    environment:
      - NODE_ENV=development
    networks:
      - golfclub-network

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    volumes:
      - ../notification-service:/app
    ports:
      - "0.0.0.0:8082:8082"  # Expose Flask notification service publicly
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/notifications.db
    networks:
      - golfclub-network
    depends_on:
      - mysql-db

volumes:
  mysql-data:

networks:
  golfclub-network:
    driver: bridge
