# Copyright (c) 2024. All rights reserved.
# docker-compose file for production purposes
# author: Dennis Grewe
version: '3'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: golfclub
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql # Persist MySQL data to a Docker volume
    networks:
      - golfclub-network

  golfclub-management:
    build:
      context: ../golfclub-management
    container_name: springboot
    volumes:
      - ../golfclub-management:/workspace
    ports:
      - "8083:8080"  # Expose backend on port 8083
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/golfclub
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      JAVA_HOME: /docker-java-home
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - mysql-db
    networks:
      - golfclub-network
    restart: always  # Restart in case of failure

  vue-frontend:
    build:
      context: ../frontend  # This is the path to the Vue.js project directory
      dockerfile: Dockerfile  # Dockerfile is in the root of the frontend directory
    container_name: vue-frontend
    volumes:
      - ../frontend:/workspace  # Mount the frontend source code for live reloading
    ports:
      - "80:8081"  # Expose port 80 for public access to Vue.js frontend
    environment:
      - NODE_ENV=production
    networks:
      - golfclub-network
    restart: always  # Ensure it restarts automatically in case of failure

  notification-service:
    build:
      context: ../notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    volumes:
      - ../notification-service:/app
    ports:
      - "8082:8082"  # Port for notification service
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:////app/notifications.db
    networks:
      - golfclub-network
    depends_on:
      - mysql-db
    restart: always

volumes:
  mysql-data: # Declare the volume for persisting MySQL data

networks:
  golfclub-network:
    driver: bridge
